<a href="https://colab.research.google.com/github/xiekg2020/DL_test/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import tensorflow as tf

x=tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [21]:
x.shape

TensorShape([12])

In [22]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [23]:
tf.reshape(x,(3,4))


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>