<a href="https://colab.research.google.com/github/xiekg2020/DL_test/blob/main/05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf

x = tf.range(4, dtype=tf.float32)
x=tf.Variable(x)

with tf.GradientTape() as t:
  y=2*tf.tensordot(x, x, axes=1)


In [8]:
x_grad=t.gradient(y,x)
x_grad

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.,  4.,  8., 12.], dtype=float32)>

In [22]:
def f(a):
  b=a*2
  while tf.norm(b) < 1000:
    b=b*2
  if tf.reduce_sum(b) > 0:
    c=b
  else:
    c=100*b
  return c

a=tf.Variable(tf.random.normal(shape=()))
with tf.GradientTape() as t:
  d=f(a)
d_grad=t.gradient(d,a)
a,d,d_grad

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-0.6034964>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-123596.055>,
 <tf.Tensor: shape=(), dtype=float32, numpy=204800.0>)