<a href="https://colab.research.google.com/github/xiekg2020/DL_test/blob/main/03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

A=tf.reshape(tf.range(20),(5,4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]], dtype=int32)>

In [2]:
tf.transpose(A)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]], dtype=int32)>

In [4]:
A.shape,A.shape[0]

(TensorShape([5, 4]), 5)

In [6]:
tf.cumsum(A,axis=0),tf.cumsum(A,axis=1)

(<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]], dtype=int32)>,
 <tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38],
        [12, 25, 39, 54],
        [16, 33, 51, 70]], dtype=int32)>)

In [7]:
B=A
A*B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]], dtype=int32)>

In [14]:
x=tf.range(4,dtype=tf.int32)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [16]:
A,x,tf.linalg.matvec(A,x)

(<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 14,  38,  62,  86, 110], dtype=int32)>)

In [17]:
B=tf.ones((4,3),tf.int32)
tf.matmul(A,B)

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[ 6,  6,  6],
       [22, 22, 22],
       [38, 38, 38],
       [54, 54, 54],
       [70, 70, 70]], dtype=int32)>

In [18]:
u=tf.constant([3.0,-4.0])
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>