<a href="https://colab.research.google.com/github/xiekg2020/DL_test/blob/main/3_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf
!pip install d2l
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

     |████████████████████████████████| 81kB 2.8MB/s 


In [3]:
def load_array(data_arrays, batch_size, is_train=True):
  dataset=tf.data.Dataset.from_tensor_slices(data_arrays)
  if is_train:
    dataset=dataset.shuffle(buffer_size=1000)
  dataset=dataset.batch(batch_size)
  return dataset

batch_size=10
data_iter=load_array((features,labels),batch_size)

In [5]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 0.66371113,  0.387428  ],
        [ 0.9730528 , -1.2075597 ],
        [ 1.1886363 ,  0.21759655],
        [ 1.2956736 , -1.798876  ],
        [ 1.1897155 , -0.85623956],
        [ 1.5175647 ,  1.1379232 ],
        [-2.2344506 , -1.0854818 ],
        [ 0.65462023, -0.36932766],
        [-0.35745472,  0.76484716],
        [ 0.5730665 ,  0.02287402]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 4.2090445 ],
        [10.234305  ],
        [ 5.8304744 ],
        [12.913767  ],
        [ 9.489014  ],
        [ 3.3677564 ],
        [ 3.423547  ],
        [ 6.7613454 ],
        [ 0.91292983],
        [ 5.2740755 ]], dtype=float32)>)

In [12]:
initializer=tf.initializers.RandomNormal(stddev=0.01)
net=tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1,kernel_initializer=initializer))
net

In [13]:
loss=tf.keras.losses.MeanSquaredError()
trainer=tf.keras.optimizers.SGD(learning_rate=0.03)

In [14]:
num_epochs=3
for epoch in range(num_epochs):
  for x,y in data_iter:
    with tf.GradientTape() as tape:
      l=loss(net(x,training=True), y)
    grads=tape.gradient(l, net.trainable_variables)
    trainer.apply_gradients(zip(grads,net.trainable_variables))
  l=loss(net(features),labels)
  print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000243
epoch 2, loss 0.000100
epoch 3, loss 0.000099


In [15]:
w=net.get_weights()[0]
print('error in estimating w', true_w-tf.reshape(w, true_w.shape))
b=net.get_weights()[1]
print('error in estimating b', true_b-b)

error in estimating w tf.Tensor([-0.00017571  0.00069785], shape=(2,), dtype=float32)
error in estimating b [-0.0002594]
