<a href="https://colab.research.google.com/github/xiekg2020/DL_test/blob/main/3_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from IPython import display
!pip install d2l
from d2l import tensorflow as d2l

batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

     |████████████████████████████████| 81kB 2.8MB/s 
4423680/4422102 [==============================] - 0s 0us/step


In [2]:
num_inputs = 784
num_outputs = 10

W = tf.Variable(
    tf.random.normal(shape=(num_inputs, num_outputs), mean=0, stddev=0.01))
b = tf.Variable(tf.zeros(num_outputs))

In [3]:
x=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
tf.reduce_sum(x,0,keepdims=True),tf.reduce_sum(x,1,keepdims=True)

(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[5., 7., 9.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[ 6.],
        [15.]], dtype=float32)>)

In [4]:
def softmax(x):
  x_exp=tf.exp(x)
  partition=tf.reduce_sum(x_exp,1,keepdims=True)
  return x_exp/partition

In [5]:
x=tf.random.normal((2,5),0,1)
x_prob=softmax(x)
x_prob,tf.reduce_sum(x_prob,1)

(<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[0.24320936, 0.1478221 , 0.43541202, 0.14809532, 0.0254612 ],
        [0.11245392, 0.16691661, 0.22853565, 0.38174516, 0.11034867]],
       dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.99999994, 1.        ], dtype=float32)>)

In [8]:
def net(x):
  return softmax(tf.matmul(tf.reshape(x,(-1,w.shape[0])),W)+b)

In [9]:
y_hat=tf.constant([[0.1,0.3,0.6],[0.3,0.2,0.5]])
y=tf.constant([0,2])
tf.boolean_mask(y_hat,tf.one_hot(y,depth=y_hat.shape[-1]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.1, 0.5], dtype=float32)>

In [10]:
def cross_entropy(y_hat,y):
  return -tf.math.log(tf.boolean_mask(y_hat,tf.one_hot(y,depth=y_hat.shape[-1])))

cross_entropy(y_hat,y)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.3025851, 0.6931472], dtype=float32)>

In [11]:
def accuracy(y_hat,y):
  if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
    y_hat=tf.argmax(y_hat,axis=1)
  cmp=tf.cast(y_hat,y.dtype)==y
  return float(tf.reduce_sum(tf.cast(cmp,y.dtype)))

In [ ]:
accuracy(y_hat,)