<a href="https://colab.research.google.com/github/xiekg2020/DL_test/blob/main/5_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

class CenteredLayer(tf.keras.Model):
    def __init__(self):
        super().__init__()

    def call(self, inputs):
        return inputs - tf.reduce_mean(inputs)

In [4]:
layer = CenteredLayer()
layer(tf.constant([1, 2, 3, 4, 5]))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-2, -1,  0,  1,  2], dtype=int32)>

In [6]:
net = tf.keras.Sequential([tf.keras.layers.Dense(128), CenteredLayer()])

In [7]:
Y = net(tf.random.uniform((4, 8)))
tf.reduce_mean(Y)

<tf.Tensor: shape=(), dtype=float32, numpy=4.656613e-10>

In [9]:
class MyDense(tf.keras.Model):
    def __init__(self, units):
        super().__init__()
        self.units = units

    def build(self, X_shape):
        self.weight = self.add_weight(
            name='weight', shape=[X_shape[-1], self.units],
            initializer=tf.random_normal_initializer())
        self.bias = self.add_weight(name='bias', shape=[self.units],
                                    initializer=tf.zeros_initializer())

    def call(self, X):
        linear = tf.matmul(X, self.weight) + self.bias
        return tf.nn.relu(linear)

In [10]:
dense = MyDense(3)
dense(tf.random.uniform((2, 5)))
dense.get_weights()

[array([[ 0.01416238, -0.0766529 ,  0.00840027],
        [ 0.04787699, -0.04576316, -0.01664669],
        [-0.01679893,  0.01018448, -0.02714211],
        [ 0.06579512, -0.0489522 , -0.0148991 ],
        [ 0.00776411,  0.00530285,  0.03917601]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [11]:
dense(tf.random.uniform((2, 5)))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.1053805 , 0.        , 0.        ],
       [0.08811656, 0.        , 0.        ]], dtype=float32)>